apiVersion: v1
kind: Pod
metadata:
  name: pod-secure-2
  namespace: audit-zone
spec:
  securityContext:
    seccompProfile:
      type: RuntimeDefault
  containers:
    - name: nginx
      image: nginx
      volumeMounts:
        - mountPath: /data
          name: safe-volume
      securityContext:
        runAsNonRoot: true
        readOnlyRootFilesystem: true
        allowPrivilegeEscalation: false
        capabilities:
          drop:
            - ALL
  volumes:
    - name: safe-volume
      emptyDir: {}
